### ISSUE TITLE
Intermitent client integration test issue

### ISSUE THREAD

**Issue by sebohe** [hashcloak/Meson#54]
```go
-- FAIL: TestClientConnectShutdown (0.02s)

panic: pki: requested epoch will never get a document [recovered]

	panic: pki: requested epoch will never get a document

goroutine 8 [running]:

testing.tRunner.func1(0xc0000d8700)

	/usr/local/go/src/testing/testing.go:874 +0x69f

panic(0xd50080, 0xc000029e40)

	/usr/local/go/src/runtime/panic.go:679 +0x1b2

github.com/katzenpost/client.AutoRegisterRandomClient(0xc000126000, 0x0, 0x0)

	/go/pkg/mod/github.com/katzenpost/client@v0.0.3-0.20191109165001-aa02bb21ca21/client.go:62 +0x1101

github.com/hashcloak/Meson-client.(*Client).Start(0xc00006e2a0, 0x0, 0x0)

	/client/client.go:32 +0x55

github.com/hashcloak/Meson-client.TestClientConnectShutdown(0xc0000d8700)

	/client/client_test.go:14 +0xc7

testing.tRunner(0xc0000d8700, 0xe35818)

	/usr/local/go/src/testing/testing.go:909 +0x19a

created by testing.(*T).Run

	/usr/local/go/src/testing/testing.go:960 +0x652
```

**Comment by Mikerah** [comment]
Closing since integration tests pass.
